//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ais.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractorsProduction
    {
        public long ordid { get; set; }
        public string name_first { get; set; }
        public string name_last { get; set; }
        public string patronymic { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public decimal price { get; set; }
    
        public virtual OrdReqs OrdReqs { get; set; }
    }
}
