//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ais.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leads
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Leads()
        {
            this.ContractorsMedia = new HashSet<ContractorsMedia>();
            this.Groups = new HashSet<Groups>();
            this.OrdReqs = new HashSet<OrdReqs>();
        }
    
        public int id { get; set; }
        public string name_first { get; set; }
        public string name_last { get; set; }
        public string patronymic { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public short prom_time { get; set; }
        public System.DateTime appeal_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractorsMedia> ContractorsMedia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Groups> Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdReqs> OrdReqs { get; set; }
    }
}
