//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ais.src.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdReqs
    {
        public long id { get; set; }
        public string prod_name { get; set; }
        public int prod_quantity { get; set; }
        public System.DateTime period_date { get; set; }
        public byte pid { get; set; }
        public Nullable<int> lid { get; set; }
    
        public virtual ContractorsProduction ContractorsProduction { get; set; }
        public virtual Leads Leads { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
