//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ais.src.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Positions
    {
        public byte uid { get; set; }
        public string department { get; set; }
        public string position { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
